"""Inventory optimization models based on Vandeput (2020)."""

from src.cost_optimization import (
    CostBreakdown,
    RSOptimizationResult,
    SQOptimizationResult,
    compare_review_periods,
    optimize_rs_policy,
    optimize_sq_policy,
    optimal_cycle_service_level_rs,
    optimal_cycle_service_level_sq,
    rs_cost_per_period,
    sq_cost_per_year,
)
from src.discrete_demand import DiscretePMF, histogram_pmf, kde_pmf, scott_bandwidth
from src.distributions import (
    DemandDistribution,
    DistributionFit,
    GammaParams,
    fit_gamma,
    gamma_loss,
    gamma_loss_inverse,
    gamma_risk_period_params,
    gamma_skewness,
    inventory_for_cycle_service_gamma,
    safety_stock_gamma,
    select_distribution,
)
from src.excel_export import gsm_allocation_to_dict, write_analysis_workbook
from src.export import write_policy_comparison, write_summary_csv
from src.fill_rate import (
    FillRateResult,
    fill_rate_from_inventory,
    fill_rate_from_safety_stock,
    inverse_standard_loss,
    normal_loss,
    normal_loss_standard,
    safety_stock_for_fill_rate,
)
from src.multi_echelon import (
    EchelonNode,
    GSMAllocation,
    GSMSimulationResult,
    echelon_inventory,
    echelon_orders,
    evaluate_serial_allocation,
    optimize_serial_gsm,
    serial_gsm_cases,
    simulate_serial_gsm,
)
from src.newsvendor import (
    NewsvendorResult,
    critical_ratio,
    muffin_pmf,
    optimal_newsvendor_continuous_normal,
    optimal_newsvendor_discrete,
)
from src.policies import PolicyResult, continuous_review_sq, periodic_review_rs
from src.risk_period import RiskPeriodStats, demand_over_risk_period
from src.safety_stock import SafetyStockResult, safety_stock, service_level_factor
from src.simulation import SimulationResult, simulate_rs_policy, simulate_sq_policy
from src.simulation_opt import (
    SimulationCostResult,
    find_best_safety_stock,
    find_best_safety_stock_smart_start,
    optimize_rs_simulation,
    simulate_rs_cost,
)

__all__ = [
    "CostBreakdown",
    "DemandDistribution",
    "DiscretePMF",
    "DistributionFit",
    "EOQResult",
    "EchelonNode",
    "FillRateResult",
    "GSMAllocation",
    "GSMSimulationResult",
    "GammaParams",
    "NewsvendorResult",
    "PolicyResult",
    "RSOptimizationResult",
    "RiskPeriodStats",
    "SQOptimizationResult",
    "SafetyStockResult",
    "SimulationCostResult",
    "SimulationResult",
    "compare_review_periods",
    "compute_eoq",
    "continuous_review_sq",
    "critical_ratio",
    "demand_over_risk_period",
    "echelon_inventory",
    "echelon_orders",
    "evaluate_serial_allocation",
    "fill_rate_from_inventory",
    "fill_rate_from_safety_stock",
    "find_best_safety_stock",
    "find_best_safety_stock_smart_start",
    "fit_gamma",
    "gamma_loss",
    "gamma_loss_inverse",
    "gamma_risk_period_params",
    "gamma_skewness",
    "histogram_pmf",
    "inventory_for_cycle_service_gamma",
    "inverse_standard_loss",
    "kde_pmf",
    "muffin_pmf",
    "normal_loss",
    "normal_loss_standard",
    "optimize_rs_policy",
    "optimize_rs_simulation",
    "optimize_serial_gsm",
    "optimize_sq_policy",
    "optimal_cycle_service_level_rs",
    "optimal_cycle_service_level_sq",
    "optimal_newsvendor_continuous_normal",
    "optimal_newsvendor_discrete",
    "periodic_review_rs",
    "rs_cost_per_period",
    "safety_stock",
    "safety_stock_for_fill_rate",
    "safety_stock_gamma",
    "scott_bandwidth",
    "select_distribution",
    "serial_gsm_cases",
    "service_level_factor",
    "simulate_rs_cost",
    "simulate_rs_policy",
    "simulate_serial_gsm",
    "simulate_sq_policy",
    "sq_cost_per_year",
    "total_cost",
    "write_policy_comparison",
    "write_summary_csv",
    "write_analysis_workbook",
    "gsm_allocation_to_dict",
]
