"""Inventory optimization models based on Vandeput (2020)."""

from src.constraints import (
    BudgetAllocation,
    InventoryItem,
    allocate_under_budget,
    apply_order_rules,
    round_up_to_multiple,
    shelf_life_max_quantity,
    total_investment,
)
from src.cost_optimization import (
    CostBreakdown,
    RSOptimizationResult,
    SQOptimizationResult,
    compare_review_periods,
    optimal_cycle_service_level_rs,
    optimal_cycle_service_level_sq,
    optimize_rs_policy,
    optimize_sq_policy,
    rs_cost_per_period,
    sq_cost_per_year,
)
from src.discrete_demand import DiscretePMF, histogram_pmf, kde_pmf, scott_bandwidth
from src.distributions import (
    DemandDistribution,
    DistributionFit,
    GammaParams,
    fit_gamma,
    gamma_loss,
    gamma_loss_inverse,
    gamma_risk_period_params,
    gamma_skewness,
    inventory_for_cycle_service_gamma,
    safety_stock_gamma,
    select_distribution,
)
from src.eoq import EOQResult, compute_eoq, total_cost
from src.excel_export import gsm_allocation_to_dict, write_analysis_workbook
from src.export import write_policy_comparison, write_summary_csv
from src.fill_rate import (
    FillRateResult,
    fill_rate_from_inventory,
    fill_rate_from_safety_stock,
    inverse_standard_loss,
    normal_loss,
    normal_loss_standard,
    safety_stock_for_fill_rate,
)
from src.forecasting import (
    ForecastResult,
    average_demand_interval,
    croston,
    forecast_demand,
    is_intermittent,
    moving_average,
    simple_exponential_smoothing,
)
from src.multi_echelon import (
    EchelonNode,
    GSMAllocation,
    GSMSimulationResult,
    echelon_inventory,
    echelon_orders,
    evaluate_serial_allocation,
    optimize_serial_gsm,
    serial_gsm_cases,
    simulate_serial_gsm,
)
from src.newsvendor import (
    NewsvendorResult,
    critical_ratio,
    muffin_pmf,
    optimal_newsvendor_continuous_normal,
    optimal_newsvendor_discrete,
)
from src.policies import PolicyResult, continuous_review_sq, periodic_review_rs
from src.powerbi_export import PowerBIDatasetPaths, build_powerbi_dataset
from src.pricing import (
    ElasticityFit,
    PriceRecommendation,
    demand_at,
    estimate_elasticity,
    fit_linear_demand,
    markdown_price,
    optimal_price_constant_elasticity,
    optimal_price_linear,
    recommend_price,
)
from src.risk_period import RiskPeriodStats, demand_over_risk_period
from src.safety_stock import SafetyStockResult, safety_stock, service_level_factor
from src.simulation import SimulationResult, simulate_rs_policy, simulate_sq_policy
from src.simulation_opt import (
    SimulationCostResult,
    find_best_safety_stock,
    find_best_safety_stock_smart_start,
    optimize_rs_simulation,
    simulate_rs_cost,
)
from src.sources import (
    CsvDemandSource,
    DataFrameDemandSource,
    DemandSource,
    SqlDemandSource,
)

__all__ = [
    "BudgetAllocation",
    "CsvDemandSource",
    "DataFrameDemandSource",
    "DemandSource",
    "SqlDemandSource",
    "InventoryItem",
    "allocate_under_budget",
    "apply_order_rules",
    "round_up_to_multiple",
    "shelf_life_max_quantity",
    "total_investment",
    "ElasticityFit",
    "PriceRecommendation",
    "estimate_elasticity",
    "demand_at",
    "optimal_price_constant_elasticity",
    "fit_linear_demand",
    "optimal_price_linear",
    "markdown_price",
    "recommend_price",
    "CostBreakdown",
    "DemandDistribution",
    "DiscretePMF",
    "DistributionFit",
    "EOQResult",
    "EchelonNode",
    "FillRateResult",
    "ForecastResult",
    "GSMAllocation",
    "GSMSimulationResult",
    "GammaParams",
    "NewsvendorResult",
    "PolicyResult",
    "PowerBIDatasetPaths",
    "RSOptimizationResult",
    "RiskPeriodStats",
    "SQOptimizationResult",
    "SafetyStockResult",
    "SimulationCostResult",
    "SimulationResult",
    "compare_review_periods",
    "average_demand_interval",
    "build_powerbi_dataset",
    "compute_eoq",
    "continuous_review_sq",
    "critical_ratio",
    "croston",
    "demand_over_risk_period",
    "echelon_inventory",
    "echelon_orders",
    "evaluate_serial_allocation",
    "fill_rate_from_inventory",
    "fill_rate_from_safety_stock",
    "find_best_safety_stock",
    "find_best_safety_stock_smart_start",
    "fit_gamma",
    "forecast_demand",
    "gamma_loss",
    "gamma_loss_inverse",
    "gamma_risk_period_params",
    "gamma_skewness",
    "histogram_pmf",
    "inventory_for_cycle_service_gamma",
    "inverse_standard_loss",
    "is_intermittent",
    "kde_pmf",
    "moving_average",
    "muffin_pmf",
    "normal_loss",
    "normal_loss_standard",
    "optimize_rs_policy",
    "optimize_rs_simulation",
    "optimize_serial_gsm",
    "optimize_sq_policy",
    "optimal_cycle_service_level_rs",
    "optimal_cycle_service_level_sq",
    "optimal_newsvendor_continuous_normal",
    "optimal_newsvendor_discrete",
    "periodic_review_rs",
    "rs_cost_per_period",
    "safety_stock",
    "safety_stock_for_fill_rate",
    "safety_stock_gamma",
    "scott_bandwidth",
    "select_distribution",
    "serial_gsm_cases",
    "service_level_factor",
    "simple_exponential_smoothing",
    "simulate_rs_cost",
    "simulate_rs_policy",
    "simulate_serial_gsm",
    "simulate_sq_policy",
    "sq_cost_per_year",
    "total_cost",
    "write_policy_comparison",
    "write_summary_csv",
    "write_analysis_workbook",
    "gsm_allocation_to_dict",
]
